#include "specs.hpp"

namespace karma::detail::specs {

const std::unordered_map<CommandFormat, std::string> kFormatToString = {
    {RM, "RM"},
    {RR, "RR"},
    {RI, "RI"},
    {J,  "J" },
};

const std::unordered_map<CommandCode, CommandFormat> kCodeToFormat = {
    {HALT,    RI},
    {SYSCALL, RI},
    {ADD,     RR},
    {ADDI,    RI},
    {SUB,     RR},
    {SUBI,    RI},
    {MUL,     RR},
    {MULI,    RI},
    {DIV,     RR},
    {DIVI,    RI},
    {LC,      RI},
    {SHL,     RR},
    {SHLI,    RI},
    {SHR,     RR},
    {SHRI,    RI},
    {AND,     RR},
    {ANDI,    RI},
    {OR,      RR},
    {ORI,     RI},
    {XOR,     RR},
    {XORI,    RI},
    {NOT,     RI},
    {MOV,     RR},
    {ADDD,    RR},
    {SUBD,    RR},
    {MULD,    RR},
    {DIVD,    RR},
    {ITOD,    RR},
    {DTOI,    RR},
    {PUSH,    RI},
    {POP,     RI},
    {CALL,    RR},
    {CALLI,   J },
    {RET,     J },
    {CMP,     RR},
    {CMPI,    RI},
    {CMPD,    RR},
    {JMP,     J },
    {JNE,     J },
    {JEQ,     J },
    {JLE,     J },
    {JL,      J },
    {JGE,     J },
    {JG,      J },
    {LOAD,    RM},
    {STORE,   RM},
    {LOAD2,   RM},
    {STORE2,  RM},
    {LOADR,   RR},
    {STORER,  RR},
    {LOADR2,  RR},
    {STORER2, RR},
};

const std::unordered_map<std::string, CommandCode> kCommandToCode = {
    {"halt",    HALT   },
    {"syscall", SYSCALL},
    {"add",     ADD    },
    {"addi",    ADDI   },
    {"sub",     SUB    },
    {"subi",    SUBI   },
    {"mul",     MUL    },
    {"muli",    MULI   },
    {"div",     DIV    },
    {"divi",    DIVI   },
    {"lc",      LC     },
    {"shl",     SHL    },
    {"shli",    SHLI   },
    {"shr",     SHR    },
    {"shri",    SHRI   },
    {"and",     AND    },
    {"andi",    ANDI   },
    {"or",      OR     },
    {"ori",     ORI    },
    {"xor",     XOR    },
    {"xori",    XORI   },
    {"not",     NOT    },
    {"mov",     MOV    },
    {"addd",    ADDD   },
    {"subd",    SUBD   },
    {"muld",    MULD   },
    {"divd",    DIVD   },
    {"itod",    ITOD   },
    {"dtoi",    DTOI   },
    {"push",    PUSH   },
    {"pop",     POP    },
    {"call",    CALL   },
    {"calli",   CALLI  },
    {"ret",     RET    },
    {"cmp",     CMP    },
    {"cmpi",    CMPI   },
    {"cmpd",    CMPD   },
    {"jmp",     JMP    },
    {"jne",     JNE    },
    {"jeq",     JEQ    },
    {"jle",     JLE    },
    {"jl",      JL     },
    {"jge",     JGE    },
    {"jg",      JG     },
    {"load",    LOAD   },
    {"store",   STORE  },
    {"load2",   LOAD2  },
    {"store2",  STORE2 },
    {"loadr",   LOADR  },
    {"storer",  STORER },
    {"loadr2",  LOADR2 },
    {"storer2", STORER2},
};

const std::unordered_map<CommandCode, std::string> kCodeToCommand =
    util::RevertMap(kCommandToCode);

const std::unordered_map<std::string, Register> kRegisterToNum = {
    {"r0", R0},
    {"r1", R1},
    {"r2", R2},
    {"r3", R3},
    {"r4", R4},
    {"r5", R5},
    {"r6", R6},
    {"r7", R7},
    {"r8", R8},
    {"r9", R9},
    {"r10", R10},
    {"r11", R11},
    {"r12", R12},
    {"r13", R13},
    {"r14", R14},
    {"r15", R15},
};

}  // namespace karma::detail::specs